forms_ejemplo1:
    resource: "@FormsBundle/Resources/config/routing/ejemplo1.yml"
    prefix:   /ejemplo1

forms_ejemplo2:
    resource: "@FormsBundle/Resources/config/routing/ejemplo2.yml"
    prefix:   /ejemplo2

forms_homepage:
    path:     /
    defaults: { _controller: FormsBundle:Default:index }
