services:
  forms.ejemplo1.person_type:
      class: FormsBundle\Form\Ejemplo1\PersonType
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
         - { name: form.type }
#    forms.example:
#        class: FormsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
