services:
    persona.validator.service:
        class: ValidacionesBundle\Service\PersonaValidatorService
#    validaciones.example:
#        class: ValidacionesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
