index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }


# AppBundle/Resources/config/routing/person.yml
person_list_neighborhoods:
    path:     /get-neighborhoods-from-city
    defaults: { _controller: "AppBundle:Person:listNeighborhoodsOfCity" }
    methods:  GET
