insert into departamento (id,provincia_id,codigo,nombre) values ('43','4','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('44','5','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('77','5','01','FRAY JUSTO SANTA MARIA DE ORO');
insert into departamento (id,provincia_id,codigo,nombre) values ('78','5','02','MAYOR LUIS J. FONTANA');
insert into departamento (id,provincia_id,codigo,nombre) values ('79','5','03','SAN FERNANDO');
insert into departamento (id,provincia_id,codigo,nombre) values ('80','5','04','TAPENAGÁ');
insert into departamento (id,provincia_id,codigo,nombre) values ('45','6','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('46','7','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('68','7','01','SAN JUSTO');
insert into departamento (id,provincia_id,codigo,nombre) values ('69','7','02','MARCOS JUAREZ');
insert into departamento (id,provincia_id,codigo,nombre) values ('70','7','03','PRESIDENTE ROQUE SAENZ PEÑA');
insert into departamento (id,provincia_id,codigo,nombre) values ('71','7','04','UNIÓN');
insert into departamento (id,provincia_id,codigo,nombre) values ('47','8','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('81','8','01','BELLA VISTA');
insert into departamento (id,provincia_id,codigo,nombre) values ('82','8','02','EMPEDRADO');
insert into departamento (id,provincia_id,codigo,nombre) values ('83','8','03','ESQUINA');
insert into departamento (id,provincia_id,codigo,nombre) values ('84','8','04','GOYA');
insert into departamento (id,provincia_id,codigo,nombre) values ('85','8','05','LAVALLE');
insert into departamento (id,provincia_id,codigo,nombre) values ('86','8','06','SALADAS');
insert into departamento (id,provincia_id,codigo,nombre) values ('41','9','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('22','9','01','PARANÁ');
insert into departamento (id,provincia_id,codigo,nombre) values ('23','9','02','URUGUAY');
insert into departamento (id,provincia_id,codigo,nombre) values ('24','9','03','CONCORDIA');
insert into departamento (id,provincia_id,codigo,nombre) values ('25','9','04','DIAMANTE');
insert into departamento (id,provincia_id,codigo,nombre) values ('26','9','05','GUALEGUAY');
insert into departamento (id,provincia_id,codigo,nombre) values ('27','9','06','GUALEGUAYCHÚ');
insert into departamento (id,provincia_id,codigo,nombre) values ('28','9','07','LA PAZ');
insert into departamento (id,provincia_id,codigo,nombre) values ('29','9','08','NOGOYÁ');
insert into departamento (id,provincia_id,codigo,nombre) values ('30','9','09','VICTORIA');
insert into departamento (id,provincia_id,codigo,nombre) values ('31','9','10','VILLAGUAY');
insert into departamento (id,provincia_id,codigo,nombre) values ('32','9','11','TALA');
insert into departamento (id,provincia_id,codigo,nombre) values ('33','9','12','COLÓN');
insert into departamento (id,provincia_id,codigo,nombre) values ('34','9','13','FEDERACIÓN');
insert into departamento (id,provincia_id,codigo,nombre) values ('35','9','14','FELICIANO');
insert into departamento (id,provincia_id,codigo,nombre) values ('36','9','15','FEDERAL');
insert into departamento (id,provincia_id,codigo,nombre) values ('37','9','16','ISLAS DEL IBICUY');
insert into departamento (id,provincia_id,codigo,nombre) values ('38','9','17','SAN SALVADOR');
insert into departamento (id,provincia_id,codigo,nombre) values ('48','10','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('49','11','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('50','12','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('51','13','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('52','14','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('53','15','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('54','16','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('55','17','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('56','18','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('57','19','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('58','20','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('59','21','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('42','22','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('1','22','01','BELGRANO');
insert into departamento (id,provincia_id,codigo,nombre) values ('2','22','02','CASEROS');
insert into departamento (id,provincia_id,codigo,nombre) values ('3','22','03','CASTELLANOS');
insert into departamento (id,provincia_id,codigo,nombre) values ('4','22','04','CONSTITUCION');
insert into departamento (id,provincia_id,codigo,nombre) values ('5','22','05','GARAY');
insert into departamento (id,provincia_id,codigo,nombre) values ('6','22','06','GENERAL LOPEZ');
insert into departamento (id,provincia_id,codigo,nombre) values ('7','22','07','GENERAL OBLIGADO');
insert into departamento (id,provincia_id,codigo,nombre) values ('8','22','08','IRIONDO');
insert into departamento (id,provincia_id,codigo,nombre) values ('9','22','09','LA CAPITAL');
insert into departamento (id,provincia_id,codigo,nombre) values ('10','22','10','LAS COLONIAS');
insert into departamento (id,provincia_id,codigo,nombre) values ('11','22','11','9 DE JULIO');
insert into departamento (id,provincia_id,codigo,nombre) values ('12','22','12','ROSARIO');
insert into departamento (id,provincia_id,codigo,nombre) values ('13','22','13','SAN CRISTOBAL');
insert into departamento (id,provincia_id,codigo,nombre) values ('14','22','14','SAN JAVIER');
insert into departamento (id,provincia_id,codigo,nombre) values ('15','22','15','SAN JERONIMO');
insert into departamento (id,provincia_id,codigo,nombre) values ('16','22','16','SAN JUSTO');
insert into departamento (id,provincia_id,codigo,nombre) values ('17','22','17','SAN LORENZO');
insert into departamento (id,provincia_id,codigo,nombre) values ('18','22','18','SAN MARTIN');
insert into departamento (id,provincia_id,codigo,nombre) values ('19','22','19','VERA');
insert into departamento (id,provincia_id,codigo,nombre) values ('60','23','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('72','23','01','JUAN FELIPE IBARRA');
insert into departamento (id,provincia_id,codigo,nombre) values ('73','23','02','GENERAL TABOADA');
insert into departamento (id,provincia_id,codigo,nombre) values ('74','23','03','BELGRANO');
insert into departamento (id,provincia_id,codigo,nombre) values ('75','23','04','AGUIRRE');
insert into departamento (id,provincia_id,codigo,nombre) values ('76','23','05','RIVADAVIA');
insert into departamento (id,provincia_id,codigo,nombre) values ('61','24','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('62','25','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('63','26','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('64','27','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('87','27','01','COLÓN');
insert into departamento (id,provincia_id,codigo,nombre) values ('88','27','02','GENERAL ARENALES');
insert into departamento (id,provincia_id,codigo,nombre) values ('89','27','03','GENERAL PINTO');
insert into departamento (id,provincia_id,codigo,nombre) values ('90','27','04','GENERAL VILLEGAS');
insert into departamento (id,provincia_id,codigo,nombre) values ('91','27','05','LEANDRO N. ALEM');
insert into departamento (id,provincia_id,codigo,nombre) values ('92','27','06','PERGAMINO');
insert into departamento (id,provincia_id,codigo,nombre) values ('93','27','07','SAN NICOLAS');
insert into departamento (id,provincia_id,codigo,nombre) values ('65','28','00','Sin Especificar');
insert into departamento (id,provincia_id,codigo,nombre) values ('66','41','00','Sin Especificar');

