insert into provincia (id,nombre,abreviatura) values ('27','BUENOS AIRES','BAI');
insert into provincia (id,nombre,abreviatura) values ('28','CAPITAL FEDERAL','CFE');
insert into provincia (id,nombre,abreviatura) values ('4','CATAMARCA','CAT');
insert into provincia (id,nombre,abreviatura) values ('5','CHACO','CHA');
insert into provincia (id,nombre,abreviatura) values ('6','CHUBUT','CHU');
insert into provincia (id,nombre,abreviatura) values ('7','CORDOBA','CBA');
insert into provincia (id,nombre,abreviatura) values ('8','CORRIENTES','CTE');
insert into provincia (id,nombre,abreviatura) values ('9','ENTRE RIOS','ERI');
insert into provincia (id,nombre,abreviatura) values ('10','FORMOSA','FOR');
insert into provincia (id,nombre,abreviatura) values ('11','JUJUY','JUJ');
insert into provincia (id,nombre,abreviatura) values ('12','LA PAMPA','LPA');
insert into provincia (id,nombre,abreviatura) values ('13','LA RIOJA','LRI');
insert into provincia (id,nombre,abreviatura) values ('14','MENDOZA','MZA');
insert into provincia (id,nombre,abreviatura) values ('15','MISIONES','MIS');
insert into provincia (id,nombre,abreviatura) values ('16','NEUQUEN','NEU');
insert into provincia (id,nombre,abreviatura) values ('17','RIO NEGRO','RNE');
insert into provincia (id,nombre,abreviatura) values ('18','SALTA','SAL');
insert into provincia (id,nombre,abreviatura) values ('19','SAN JUAN','SJU');
insert into provincia (id,nombre,abreviatura) values ('20','SAN LUIS','SLU');
insert into provincia (id,nombre,abreviatura) values ('21','SANTA CRUZ','SCR');
insert into provincia (id,nombre,abreviatura) values ('22','SANTA FE','SFE');
insert into provincia (id,nombre,abreviatura) values ('23','SANTIAGO DEL ESTERO','SDE');
insert into provincia (id,nombre,abreviatura) values ('24','SIN PROVINCIA','SIN');
insert into provincia (id,nombre,abreviatura) values ('25','TIERRA DEL FUEGO','TDF');
insert into provincia (id,nombre,abreviatura) values ('26','TUCUMAN ','TUC');
insert into provincia (id,nombre,abreviatura) values ('41','Sin Especificar','---');
